### ISSUE TITLE
如何自定义出现的下拉关键词？

### ISSUE THREAD

**Issue by 2450184176** [zjfcool/vue2x-ace-editor#1]
比方说当我输入‘select * from fooDb.'时，下拉就出现该库里的表的数据。

**Comment by zjfcool** [comment]
@2450184176 
可以参考[example/src/views/setcomplete.vue](https://github.com/zjfcool/vue2x-ace-editor/blob/master/example/src/views/SetComplete.vue),当editorchange时从后端实时拉数据过来渲染下拉关键词，可用websocket更快稳定些。
