### ISSUE TITLE
VueAceEditor  Throw Error

### ISSUE THREAD

**Issue by WeMissing** [zjfcool/vue2x-ace-editor#5]
vm.js:91 Uncaught F:\Electron\ZJICX\node_modules\vue2x-ace-editor\index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import VueAceEditor from './editor/src/main.vue';
                                                                                                                                                                  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:265:10)
    at Object.runInThisContext (vm.js:313:10)
    at Module._compile (internal/modules/cjs/loader.js:712:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at eval (webpack-internal:///vue2x-ace-editor:1:18)

**Comment by zjfcool** [comment]
> vm.js:91 Uncaught F:\Electron\ZJICX\node_modules\vue2x-ace-editor\index.js:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import VueAceEditor from './editor/src/main.vue';
> ^^^^^^^^^^^^
> 
> SyntaxError: Unexpected identifier
> at new Script (vm.js:83:7)
> at createScript (vm.js:265:10)
> at Object.runInThisContext (vm.js:313:10)
> at Module._compile (internal/modules/cjs/loader.js:712:26)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
> at Module.load (internal/modules/cjs/loader.js:645:32)
> at Function.Module._load (internal/modules/cjs/loader.js:560:12)
> at Module.require (internal/modules/cjs/loader.js:685:19)
> at require (internal/modules/cjs/helpers.js:16:16)
> at eval (webpack-internal:///vue2x-ace-editor:1:18)

you can refer to this [example](https://github.com/zjfcool/vue2x-ace-editor/blob/master/example/src/main.js)
